### PR TITLE
fix: add `./` to relative path on publish

### LINKED ISSUE #51: monorepo with workspaces fails to publish to npm
I am experiencing the exact same issue described here:
https://github.com/npm/cli/issues/2796

I am running on npm 7 on a on MacOS.

when the plugin runs `npm publish packages/projectA --tag latest --dry-run` from project's root folder it fails like the description above.

it works you add `./` to the path so that the commands instead becomes `npm publish ./packages/projectA --tag latest --dry-run`

Note: in my case the name in package.json for projectA is different from the folder name. So it might get fixed by #50 as well as #53

### PR DESCRIPTION
**Pull request by nilzona**
closes #51

### CODE REVIEW

**Comment by stefanvanherwijnen** [comment]
With this PR it does not seem to read the current version for me:

🚀 Let's release package (currently at 0.0.0)

**Comment by scalvert** [comment]
Is this specifically looking at resolving the compatibility issue with npm v7? Just trying to confirm the scope of the problem.

**Comment by scalvert** [comment]
Reading the referenced issue this seems to be the case. Thanks for this PR. I'll verify this, as I have a package that I ran into this problem with that also needs a publish.

**Comment by nilzona** [comment]
hey @scalvert. I actually didn't test this with npm < v7 so I can't tell for sure, but from what I can read this is a npm 7 problem as you pointed out and also a npm 6 problem if the folder name was different from the package name (not verified by me though).

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Thank you @nilzona!

**Pull request merged**
